### ISSUE TITLE
Getting this error when trying to use the Dropbox Paper Finder workflow

### ISSUE THREAD

**Issue by annakelian** [tomoyukikashiro/dropbox-paper-alfred-workflow#1]
Starting debug for 'Dropbox Paper Finder'

[2019-01-09 14:05:31][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "/Users/webflow/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/91798A10-57E2-4CF1-8A2F-6C9A8911A968", line 3, in <module>
    import requests
ImportError: No module named requests
[2019-01-09 14:05:32][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "/Users/webflow/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/4385FEF2-2C79-4AD3-91F8-88757D5E7D18", line 3, in <module>
    import requests
ImportError: No module named requests
[2019-01-09 14:05:34][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "/Users/webflow/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/1CD05A21-BEEE-4070-A2D4-1FC01230175B", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by t-jindai** [comment]
@annakelian Sorry for that. I fixed it so plz download from here.

https://github.com/tomoyukikashiro/dropbox-paper-alfred-workflow/releases/latest
